apiVersion: v1
kind: Service
metadata:
  name: nullroute-bgp
  namespace: nullroute
  annotations:
    metallb.io/address-pool: local-pool
    metallb.io/loadBalancerIPs: 10.0.39.197,2001:470:3838:39::197
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: nullroute
  ports:
    - name: bgp
      port: 179
      targetPort: 179
      protocol: TCP
