apiVersion: v1
kind: Service
metadata:
  name: nullroute-bgp
  namespace: nullroute
  annotations:
    metallb.io/address-pool: local-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.39.197
  selector:
    app: nullroute
  ports:
    - name: bgp
      port: 179
      targetPort: 179
      protocol: TCP
