FROM golang:1.24 AS builder
WORKDIR /src
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install github.com/osrg/gobgp/v3/cmd/gobgpd@v3.37.0

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /go/bin/gobgpd /usr/local/bin/gobgpd
ENTRYPOINT ["/usr/local/bin/gobgpd"]
