apiVersion: v1
kind: ConfigMap
metadata:
  name: nullroute-config
  namespace: networking
data:
  config.yaml: |
    interval: 30m
    run_once: false
    state_file: /var/lib/nullroute/state.txt
    gobgp_bin: /usr/local/bin/gobgp
    blackhole_community: "65535:666"
    min_prefix_v4: 24
    min_prefix_v6: 48
    sources:
      - name: team-cymru-fullbogons-v4
        url: https://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt
      - name: team-cymru-fullbogons-v6
        url: https://www.team-cymru.org/Services/Bogons/fullbogons-ipv6.txt
      - name: spamhaus-drop
        url: https://www.spamhaus.org/drop/drop.txt
      - name: spamhaus-edrop
        url: https://www.spamhaus.org/drop/edrop.txt
      - name: firehol-level1
        url: https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset
  gobgpd.yaml: |
    global:
      config:
        as: 65010
        router-id: 10.255.255.10
    neighbors:
      - config:
          neighbor-address: 10.255.255.1
          peer-as: 65001
        afi-safis:
          - config:
              afi-safi-name: ipv4-unicast
          - config:
              afi-safi-name: ipv6-unicast
